name: Main

on:
  push:
    branches:
      - main

env:
  REPO: docker.pkg.github.com/${{ github.repository }}/lambda-rust

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: make test
  publish:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        shell: bash
        run: make build
      - name: Publish
        shell: bash
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login -u ${{ github.actor }} --password-stdin docker.pkg.github.com
          make publish